FROM apache/spark:3.5.0

USER root

# Install system dependencies if needed (e.g., for building python packages)
# RUN apt-get update && apt-get install -y build-essential

# Install Python dependencies
RUN pip install pandas happybase thrift streamlit plotly

# USER 1001
